---
- name: Watch for new incidents in ServiceNow
  hosts: localhost
  sources:
    - name: Listen to ServiceNow
      cloin.eda.snow_records:
        instance: "{{ snow_instance }}"
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        table: incident
        interval: 1
  rules:
    - name: Augment Incident
      condition: event.cmdb_ci is defined
      actions:
        - debug:
            var: event
        - run_job_template:
            organization: "midrange"
            name: "augment-incident"
    - name: Debug everything else
      condition: event.cmdb_ci is not defined
      action:
        debug:
          var: event
  vars:
    snow_instance: "{{ lookup('env', 'SNOW_INSTANCE') }}"
    snow_username: "{{ lookup('env', 'SNOW_USERNAME') }}"
    snow_password: "{{ lookup('env', 'SNOW_PASSWORD') }}"
